version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 blog_project_v2.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpassword
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
